### ISSUE TITLE
Free as in Speech

### ISSUE THREAD

**Issue by ldwoolley** [jwinnie/promotelinux.org#2]
The traditional quote for free Linux is usually something along the lines of `Free as in speech and free as in beer`.  Because context is insufficient to identify which free, you correctly identify it with the French or Spanish term `libre` to distinguish the free as speech side.  So to make it logically strong you need to do the same on the `free as in beer` side.  The normal word from French or Spanish is `Gratis`.  So the first sentences could be something like:
> Linux is Free/Libre Software (Open Source Software) and you will always have access to the source code.
> Linux is often Free/Gratis Software (Distributed free of charge) and will likely always be that way, because it has been Liberated.

**Comment by jepotter1-archive** [comment]
The Free Software philosophy part was difficult to write as I wanted to make it very clear, even to people who have never used Linux or care about software licenses. That is why I left out many parts, since it was meant to be a persuasive introduction to free software, not an explanation. People who found my introduction interesting can click the link to the in-depth article from the Free Software Foundation.

If anyone has a better way of explaining it, please submit a pull request.

**Comment by ldwoolley** [comment]
Most development paths want to discuss an issue and then close it if no resolution is found, or in the discussion propose something agreeable.  Then a pull request is made to submit a solution that matches the approved idea.  Then in the pull request improvements to the solution are managed before joining if applicable.

**Comment by jepotter1-archive** [comment]
I rewrote the "Free Software" description in f818e2d and it is now (hopefully) a little bit more clear.
